name: staging
url: http://localhost:3000
protection_rules:
  - required_reviewers:
      - tobac
  - wait_timer:
      minutes: 5
  - required_status_checks:
      - "build-and-test"
      - "security-checks"
      - "database-check"
